### ISSUE TITLE
error when I open my epub

### ISSUE THREAD

**Issue by bilal333** [pgaskin/ePubViewer#5]
{"error":"TypeError: Cannot read property 'substr' of undefined","stack":"TypeError: Cannot read property 'substr' of undefined\n at Archive.getBlob (http://localhost/ePubViewer/libs/epub.js:16017:14)\n at Archive.createUrl (http://localhost/ePubViewer/libs/epub.js:16104:21)\n at App.onBookCoverLoaded (http://localhost/ePubViewer/script.js:342:29)"}
[IKITAB_EPUB_000027_01 (copy).zip](https://github.com/geek1011/ePubViewer/files/2716374/IKITAB_EPUB_000027_01.copy.zip)

**Comment by pgaskin** [comment]
This looks like an issue with the resources (images/CSS) in your epub. I'll try and figure out exactly what when I'm at my computer.

**Comment by justxuewei** [comment]
Yes, I got that problem too. Is there any way to fix it?

**Comment by aledemajo** [comment]
I can't reproduce this problem. The file attached by @bilal333 renders correctly, no errors on the console

tested locally on latest version
Browser: Chrome Version 84.0.4147.89 (Official Build) (64-bit) 

maybe someone could confirm this behavior and this issue could be closed? 😄

**Comment by 1029098564** [comment]
man,ha ha ha~,what can i say
